// eslint-disable-next-line import/prefer-default-export
export const tableData = [
  {
    title: 'position',
    columns: [
      'Token',
      'Quantity',
      'Position Size',
      'Entry Prize',
      'Mark Prize',
      'Collateral',
      'Pnl',
      'TP/SL',
      'Liquidation Price',
      'Fees',
    ],
    data: [
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
      {
        Token: 'SOL',
        Quantity: '20.00',
        'Position Size': '3',
        'Entry Prize': '230',
        'Mark Prize': '200',
        Collateral: '125',
        Pnl: null,
        'TP/SL': null,
        'Liquidation Price': 10,
        Fees: '1221.12',
      },
    ],
  },
  {
    title: 'open-orders',
    columns: [
      'Date',
      'Token',
      'Quantity',
      'Position Size',
      'Mark Price',
      'Collateral',
      'TP/SL',
      'Fees',
    ],
    data: [
      {
        Date: '1',
        Token: 'SOL',
        Quantity: '1',
        'Position Size': '1',
        'Mark Price': null,
        Collateral: null,
        'TP/SL': '1',
        Fees: '1',
      },
      {
        Date: '1',
        Token: 'SOL',
        Quantity: '1',
        'Position Size': '1',
        'Mark Price': null,
        Collateral: null,
        'TP/SL': '1',
        Fees: '1',
      },
      {
        Date: '1',
        Token: 'SOL',
        Quantity: '1',
        'Position Size': '1',
        'Mark Price': null,
        Collateral: null,
        'TP/SL': '1',
        Fees: '1',
      },
    ],
  },
  {
    title: 'balance',
    columns: ['Token', 'Amount(USDC)'],
    data: [
      { Token: 'SOL', 'Amount(USDC)': '1' },
      { Token: 'SOL', 'Amount(USDC)': '1' },
      { Token: 'SOL', 'Amount(USDC)': '1' },
    ],
  },
  {
    title: 'order-history',
    columns: [
      'Date',
      'Type',
      'Position Size',
      'Collateral',
      'Order Value',
      'Trigger Price',
      'Order Status',
    ],
    data: [
      {
        Date: '2',
        Type: '2',
        'Position Size': '2',
        Collateral: '2',
        'Order Value': '2',
        'Trigger Price': '2',
        'Order Status': null,
      },
      {
        Date: '2',
        Type: '2',
        'Position Size': '2',
        Collateral: '2',
        'Order Value': '2',
        'Trigger Price': '2',
        'Order Status': null,
      },
      {
        Date: '2',
        Type: '2',
        'Position Size': '2',
        Collateral: '2',
        'Order Value': '2',
        'Trigger Price': '2',
        'Order Status': null,
      },
    ],
  },
  {
    title: 'history',
    columns: [
      'Date',
      'Type',
      'Quantity',
      'Position Size',
      'Entry Price',
      'Quantity',
      'Closed PnL',
      'Fees',
    ],
    data: [
      {
        Date: '1',
        Token: 'SOL',
        'Position Size': '1',
        'Entry Price': null,
        Quantity: null,
        'Closed PnL': null,
        Fees: null,
      },
      {
        Date: '1',
        Token: 'SOL',
        'Position Size': '1',
        'Entry Price': null,
        Quantity: null,
        'Closed PnL': null,
        Fees: null,
      },
      {
        Date: '1',
        Token: 'SOL',
        'Position Size': '1',
        'Entry Price': null,
        Quantity: null,
        'Closed PnL': null,
        Fees: null,
      },
    ],
  },
];
